# Generated by Django 4.0.2 on 2023-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
